python main.py \
    --eva_step 1000 \
    --do_train \
    --do_valid \
    --max_seq_length 512 \
    --model_name "bert-base-chinese" \
    --save_name "bert-base-test" \
    --train_batch_size 16 \
    --valid_batch_size 16 \
    --lr 5e-5 \
    --num_train_epochs 10 \
    --gpu_idx 1 \
    --fp16 \
    --seed 100 \
